### Index method
GET http://localhost:3000/api/timesheets



### Successfully post a timesheet
POST http://localhost:3000/api/timesheets
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTE4MTYyMTgsInN1YiI6NH0.wWXHa_GDifl9njn8fV4LwNBM9AX7BGZXkwPOu8yGvLs


{
    "user_id": 4,
    "name": "Andrew",
    "date": "25.01.21",
    "start_time": "12:00pm",
    "end_time": "4:00pm",
    "total_hours": 4,
    "comments": "testing testing testing!"
}



### Unsuccessfully post a timesheet



### Show timesheet id: 2
GET http://localhost:3000/api/timesheets/2



### Show timesheet id: 1000
GET http://localhost:3000/api/timesheets/1000



### Successfully update timesheet 5
PUT http://localhost:3000/api/timesheets/17
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIwNzExODAsInN1YiI6MX0.WxyKjwCehKTFfoELmLetsgy3YzcwNrNv5x-XFRLAITE


{
    "user_id": 1,
    "date": "25.01.21",
    "start_time": "6:00am",
    "end_time": "1:00pm",
    "total_hours": 7,
    "comments": "Does update work?"
}



### Successfully delete timesheet with id 1
DELETE http://localhost:3000/api/timesheets/1



### Create a user
POST http://localhost:3000/api/auth/sign_up
Content-Type: application/json

{
    "username": "bianc",
    "email": "bianc@test.com",
    "password": "password",
    "password_confirmation": "password"

}



### Sign in with correct details
POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{
    "email": "sam@test.com",
	"password": "password"
}



### Sign in with incorrect details
POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{
    "email": "harry@test.com",
	"password": "password1"
}



### Destroy timesheet I have permission for
DELETE http://localhost:3000/api/timesheets/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTE3MjgyMzgsInN1YiI6MX0.M1eU7qWFLprad4Gqll8vXSvNlKEzq4G0QWijat3gzWs