### Index method
GET http://localhost:3000/api/timesheets



### Successfully post a timesheet
POST http://localhost:3000/api/timesheets
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTE3MjczMjAsInN1YiI6NH0.IFiPcShnQqBL99ntQJ0FMSjT1Qmb7u-UpoeP25OMVRQ


{
    "name": "Andrew",
    "date": "25.01.21",
    "start_time": "12:00pm",
    "end_time": "4:00pm",
    "total_hours": 4,
    "comments": "I prefer design!"
}



### Unsuccessfully post a timesheet



### Show timesheet id: 2
GET http://localhost:3000/api/timesheets/2



### Show timesheet id: 1000
GET http://localhost:3000/api/timesheets/1000



### Successfully update timesheet 1
PUT http://localhost:3000/api/timesheets/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTE3MjgyMzgsInN1YiI6MX0.M1eU7qWFLprad4Gqll8vXSvNlKEzq4G0QWijat3gzWs


{
    "date": "25.01.21",
    "start_time": "6:00am",
    "end_time": "1:00pm",
    "total_hours": 7,
    "comments": "Client was happy with the work"
}



### Successfully delete timesheet with id 1
DELETE http://localhost:3000/api/timesheets/1



### Create a user
POST http://localhost:3000/api/auth/sign_up
Content-Type: application/json

{
    "username": "Test",
    "email": "test@test.com",
    "password": "password",
    "password_confirmation": "password"

}



### Sign in with correct details
POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{
    "email": "sam@test.com",
	"password": "password"
}



### Sign in with incorrect details
POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{
    "email": "sam@test.com",
	"password": "password1"
}



### Destroy timesheet I have permission for
DELETE http://localhost:3000/api/timesheets/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTE3MjgyMzgsInN1YiI6MX0.M1eU7qWFLprad4Gqll8vXSvNlKEzq4G0QWijat3gzWs